/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Implementacion.ImplPersona;
import conexion.ConexionSqlite;
import entidades.Persona;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maruja
 */
public class Eliminar extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    public Eliminar() {
        initComponents();
        ConexionSqlite cnx = new ConexionSqlite();
                
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellido paterno");
        modelo.addColumn("Apellido materno");
        modelo.addColumn("Direccion");
        modelo.addColumn("Correo");
        modelo.addColumn("Numero de celular");
        modelo.addColumn("Años de edad");
        modelo.addColumn("DNI");
        modelo.addColumn("Nivel de educacion");
        modelo.addColumn("Estado civil");
        modelo.addColumn("Genero");
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        this.jTable1_reporte.setModel(modelo);
        
        
       
        try {
           Statement st = cnx.getConnect().createStatement();
           String query = "select * from personas";
           ResultSet rs = st.executeQuery(query);
           
           
           while(rs.next()){
           Persona p = new Persona();
           
           p.setId(rs.getString("PER_ID"));
           p.setNombres(rs.getString(2));
           p.setApellido_pater(rs.getString(3));
           p.setApellido_mater(rs.getString(4));
           p.setDireccion(rs.getString(5));
           p.setCorreo(rs.getString(6));
           p.setNum_celular(rs.getString(7));
           p.setAnios_edad(rs.getString(8));
           p.setDni(rs.getString(9));
           p.setNivel_educacion(rs.getObject(10));
           p.setEstado_civil(rs.getObject(11));
           p.setGenero(rs.getObject(12));
           p.setUsuario(rs.getString(13));
           p.setContrasenia(rs.getString(14));
           
        String info[] = new String[14];
        info[0]= p.getId();
        info[1]= p.getNombres();
        info[2]= p.getApellido_pater();
        info[3]= p.getApellido_mater();
        info[4]= p.getDireccion();
        info[5]= p.getCorreo();
        info[6]= p.getNum_celular();
        info[7]= p.getAnios_edad();
        info[8]= p.getDni();
        info[9]= ""+p.getNivel_educacion();
        info[10]= ""+p.getEstado_civil();
        info[11]= ""+p.getGenero();
        info[12]=p.getUsuario();
        info[13]= "********";
        modelo.addRow(info);
           
         
           
           }
           
     
        } catch (SQLException ex) {
            Logger.getLogger(ImplPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_reporte = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1_eliminar = new javax.swing.JButton();
        jTextField1_id = new javax.swing.JTextField();

        setTitle("Eliminar");

        jTable1_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title1", "Title 2", "Title 3", "Title 4", "null", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14"
            }
        ));
        jScrollPane1.setViewportView(jTable1_reporte);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Eliminar");

        jLabel2.setText("Ingresa el ID para eliminar");

        jButton1_eliminar.setText("Eliminar");
        jButton1_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(jButton1_eliminar)))
                .addContainerGap(1039, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addComponent(jButton1_eliminar)
                .addGap(0, 336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_eliminarActionPerformed
        ImplPersona imple = new ImplPersona();
        Persona e = new Persona();

        e.setId(jTextField1_id.getText());
    
        imple.eliminarpersonas(e);
    }//GEN-LAST:event_jButton1_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_reporte;
    private javax.swing.JTextField jTextField1_id;
    // End of variables declaration//GEN-END:variables
}
